In [1]:
import numpy as np

In [28]:
a = np.array([1, 17, 34, 2, 23, 9, 18, 17, 30, 11])
a

array([ 1, 17, 34,  2, 23,  9, 18, 17, 30, 11])

In [9]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
print(a.reshape((5, 2)))
print(a.shape)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
(10,)


In [16]:
a.reshape(5, 2) #The same as above

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [30]:
print(a.reshape(len(a),1,1))
print(a.shape)

[[[ 1]]

 [[17]]

 [[34]]

 [[ 2]]

 [[23]]

 [[ 9]]

 [[18]]

 [[17]]

 [[30]]

 [[11]]]
(10,)


In [32]:
a.reshape(10, 1, 1)

array([[[ 1]],

       [[17]],

       [[34]],

       [[ 2]],

       [[23]],

       [[ 9]],

       [[18]],

       [[17]],

       [[30]],

       [[11]]])

In [34]:
import pandas as pd

In [35]:
b = pd.DataFrame({'X':[1, 17, 34, 2, 23, 9, 18, 17, 30, 11],
                  'Y':[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
    
})
b

X   Y
0   1  10
1  17   9
2  34   8
3   2   7
4  23   6
5   9   5
6  18   4
7  17   3
8  30   2
9  11   1

In [38]:
b_array = np.array(b.X).reshape(len(b), 1, 1)
print(b_array)
print(b_array.shape)

[[[ 1]]

 [[17]]

 [[34]]

 [[ 2]]

 [[23]]

 [[ 9]]

 [[18]]

 [[17]]

 [[30]]

 [[11]]]
(10, 1, 1)


In [40]:
b_list = b.X.to_list()
print(type(b_list))
print(b_list)

<class 'list'>
[1, 17, 34, 2, 23, 9, 18, 17, 30, 11]


In [63]:
b_array[1:2]

array([[[17]]], dtype=int64)

In [45]:
#Resources: https://github.com/jeffheaton/t81_558_deep_learning/blob/master/t81_558_class_10_2_lstm.ipynb

def to_sequences(SEQUENCE_SIZE, obs):
    x = []
    y = []

    for i in range(len(obs)-SEQUENCE_SIZE):
        #print(i)
        window = obs[i:(i+SEQUENCE_SIZE)]
        after_window = obs[i+SEQUENCE_SIZE]
        window = [[x] for x in window]
        #print("{} - {}".format(window,after_window))
        x.append(window)
        y.append(after_window)
        
    return np.array(x),np.array(y)
