In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3], dtype = 'int8')
a

array([1, 2, 3], dtype=int8)

In [3]:
a.dtype

dtype('int8')

In [4]:
a.ndim
#3 elements, whislt restored in one single dimension

1

In [5]:
a.shape

(3,)

In [6]:
### Larger size
b = np.array([[1, 2, 3], [4, 5, 6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
b.dtype

dtype('int32')

In [8]:
b.ndim

2

In [9]:
b.shape #2 rows, 3 cols

(2, 3)

In [10]:
#Get specific value
ex1 = a[2]; print(ex1)
#Fet 5 in array b
ex2 = b[1, 1]; print(ex2)
ex3 = b[1, -2]; print(ex3) #negative sign is used to count back from a series

3
5
5


In [11]:
#Nested forms
c = np.array([[[1, 2], [3, 4]],
              [[4, 5], [6, 7]],
              [[8, 9], [10, 11]]])
c

array([[[ 1,  2],
        [ 3,  4]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [12]:
c.shape
#(outer_dim, middle_dim, inner_dim)

(3, 2, 2)

In [13]:
d = np.array([[[1]], [[2]], [[3]],
               [[4]], [[5]], [[6]],
               [[7]], [[8]], [[9]]])
d

array([[[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]],

       [[6]],

       [[7]],

       [[8]],

       [[9]]])

In [14]:
d.shape

(9, 1, 1)

In [15]:
#Get the value from nested structured data
#Get number 7 in array
c1 = c[1, 1, 1]
#Get 10
c2 = c[2, 1, 0]

#Assign new value to the specific: Assign -9999 to the number 4 in array c
c[1, 0, 0] = -9999
c

array([[[    1,     2],
        [    3,     4]],

       [[-9999,     5],
        [    6,     7]],

       [[    8,     9],
        [   10,    11]]])

In [16]:
#Select all the sets, or either all the rows or columns in a set
c3 = c[:, 1, :] #All sets, second rows in those sets, all columns in those rows
#print(c3)

c_f = c[1, :, 1]
c_f

array([5, 7])

In [17]:
#Replace the nested array values
c_f = c[:, 0, :]
#print(c_f)
c_f = np.array([[77, 88],
                [99, 111],
                [222, 333]])
c_f

array([[ 77,  88],
       [ 99, 111],
       [222, 333]])

### Initialisation

In [18]:
#Zero matrix
np.zeros((2, 2)) #2 by 2 zero matrix

array([[0., 0.],
       [0., 0.]])

In [19]:
np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [20]:
#All ones matrix
np.ones((2, 4), dtype = 'int8')

array([[1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int8)

In [21]:
#Define value to fill in matrix
np.full(shape = (2, 3), fill_value = 99) #2 by 3 matrix, with all 99 in values

array([[99, 99, 99],
       [99, 99, 99]])

In [22]:
#Reuse the existing shape of an array, and then fill in with the same value
#Use the shape of array b to create a b-shaped array
print(np.full(shape = b.shape, fill_value = 77)) 
print('-----------------full_like()-----------------------')
print(np.full_like(b, 77))

[[77 77 77]
 [77 77 77]]
-----------------full_like()-----------------------
[[77 77 77]
 [77 77 77]]


Generate random-numbered matrix 

In [23]:
#Value: 0 to 1, defining shapes/size can work
rand_matrix = np.random.rand(3, 2)
rand_matrix

array([[0.14777916, 0.99847558],
       [0.71934933, 0.67178507],
       [0.62560378, 0.17547964]])

In [24]:
#Define matrix with assigned range for random values
rand_int_matrix = np.random.randint(low = 1, high = 17, size = (3, 2))
rand_int_matrix

array([[12,  6],
       [13,  8],
       [ 7,  5]])

Identity Matrix

In [25]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Repeat

In [26]:
np.repeat(a = 3, repeats = 4) 

array([3, 3, 3, 3])

In [27]:
np.repeat(a = np.array([3, 4]), repeats = 4, axis = 0)

array([3, 3, 3, 3, 4, 4, 4, 4])

In [28]:
np.repeat(a = np.array([[3], [4]]), repeats = 4, axis = 0)

array([[3],
       [3],
       [3],
       [3],
       [4],
       [4],
       [4],
       [4]])

In [29]:
np.repeat(a = np.array([[3], [4]]), repeats = 4, axis = 0)

array([[3],
       [3],
       [3],
       [3],
       [4],
       [4],
       [4],
       [4]])

In [30]:
in_put = np.array([[3, 4, 5]])
np.repeat(a = in_put, repeats = 4, axis = 0)

array([[3, 4, 5],
       [3, 4, 5],
       [3, 4, 5],
       [3, 4, 5]])

In [31]:
#Fancy
#5 by 5 matrix with outer frame being filled by zero
#Inside the matrix has inner frame with 1
#At the centre be 9
zero = np.zeros((5, 5))
print(zero)

inner = np.ones((3, 3))
print(inner)

inner[1, 1] = 9
print(inner)

#Final replacement 
zero[1:4, 1:4] = inner #This is exclusive index so it will end with a non-included index value when selecting the range of rows/cols
print(zero)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 9. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 9. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


### Copy

Consider a single numpy array named a. If we let another numpy array b equal a, and we change the value in array b, so will the corresponding value in array a will be changed subsequently.
To avoid this, .copy() must be used.

In [32]:
a = np.array([1, 2, 3])

b = a 
print(a)
print(b)

b[0] = -9999
print(b)
print(a)

[1 2 3]
[1 2 3]
[-9999     2     3]
[-9999     2     3]


In [33]:
#.copy() function
a = np.array([1, 2, 3])
b = a.copy()

b[0] = -9999
print(b)
print(a)

[-9999     2     3]
[1 2 3]


### Math: some simple demos

In [34]:
#Matrix multiplications: np.matmul() func.
m = np.full((2, 3), 2)
n = np.full((3, 2), 3)

print(m)
print(n)

mul = np.matmul(m, n)
print(mul)

[[2 2 2]
 [2 2 2]]
[[3 3]
 [3 3]
 [3 3]]
[[18 18]
 [18 18]]


In [35]:
n ** 2

array([[9, 9],
       [9, 9],
       [9, 9]], dtype=int32)

In [36]:
np.cos(n)

array([[-0.9899925, -0.9899925],
       [-0.9899925, -0.9899925],
       [-0.9899925, -0.9899925]])

### Statistics

In [37]:
stats = np.array([[1, 2, 3], [4, 5, 11]])
stats

array([[ 1,  2,  3],
       [ 4,  5, 11]])

In [38]:
median = np.median(stats)
print(median)

mean = np.mean(stats)
print(mean)

std = np.std(stats)
print(std)

3.5
4.333333333333333
3.2489314482696545


In [39]:
#Specify the rows or cols to calculate
np.mean(stats[0])

2.0

In [40]:
np.max(stats[1])

11

In [41]:
np.min(stats[0][0])

1

In [42]:
# Return an array of specified statistics out of general comparison within the rows 
np.max(stats, axis = 1)

array([ 3, 11])

In [43]:
# Return an array of specified statistics out of vertical comparison amid or amongst the cols
np.max(stats, axis = 0)

array([ 4,  5, 11])

In [44]:
np.min(stats, axis = 1)

array([1, 4])

In [45]:
np.sum(stats) #Sum up the value through all argument in the array

26

In [46]:
# Sum the value vertically through the cols
np.sum(stats, axis = 0)

array([ 5,  7, 14])

In [47]:
# Sum the value horizontally along the rows
np.sum(stats, axis = 1)

array([ 6, 20])

Notice that the axis value is not as same as the index that series or dataframe data in pandas refers to.

### Reshape

In [48]:
array = np.array([[1, 2, 3, 4, 5], 
                [11, 22, 33, 44, 55], 
                [13, 14, 15, 16, 17]])
array

array([[ 1,  2,  3,  4,  5],
       [11, 22, 33, 44, 55],
       [13, 14, 15, 16, 17]])

In [49]:
array.shape

(3, 5)

In [50]:
#Reshape the array into new form
array2 = array.reshape(5, 3)
print(array2)

[[ 1  2  3]
 [ 4  5 11]
 [22 33 44]
 [55 13 14]
 [15 16 17]]


In [51]:
array2 = array.reshape((15, 1, 1))
print(array2)

[[[ 1]]

 [[ 2]]

 [[ 3]]

 [[ 4]]

 [[ 5]]

 [[11]]

 [[22]]

 [[33]]

 [[44]]

 [[55]]

 [[13]]

 [[14]]

 [[15]]

 [[16]]

 [[17]]]


### Stack

In [52]:
#Vertically stack up arrays
v1 = np.array([1, 2, 3, 4])
v2 = np.array([4, 5, 6, 7])

np.vstack([v1, v2]) #np.vstack((v1, v2)) #Parameter ust be in tuple type

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [53]:
#Horizontally stack up arrays
h1 = np.array([1, 2 , 3, 4])
h2 = np.array([4, 5, 6, 7])

np.hstack((h1, h2))

array([1, 2, 3, 4, 4, 5, 6, 7])

In [54]:
np.vstack((v1, v2, v2, v2, v2))

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [4, 5, 6, 7],
       [4, 5, 6, 7],
       [4, 5, 6, 7]])

### Indexing and Boolean Values 

In [55]:
array

array([[ 1,  2,  3,  4,  5],
       [11, 22, 33, 44, 55],
       [13, 14, 15, 16, 17]])

In [56]:
array > 20

array([[False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [False, False, False, False, False]])

In [57]:
#By condition
array[array > 20]

array([22, 33, 44, 55])

In [58]:
#Select 11, 22, 13, 14 at the same time
array[1:3, 0:2] #Excluding 

array([[11, 22],
       [13, 14]])

In [59]:
#Diagnal selection
array[[1, 2], [0, 1]]

array([11, 14])

In [60]:
#Select 1, 22, 15
array[[0, 1, 2], [0, 1, 2]]

array([ 1, 22, 15])

In [61]:
#Select 4, 5 16, 17
array[[0, 2], 3:] #Consecutive index selection using : from index/position to index/position

array([[ 4,  5],
       [16, 17]])

In [62]:
array[[0, 2], [3, 4]] #, is used to seperate and to select the single index/position.

array([ 4, 17])

In [63]:
#Pass a list (turns out to be index list) and get the corresponding values
example = np.array([11, 37, 58, 59, 66, 72])
example[[1, 2, 3]]

array([37, 58, 59])

Boolean masking

In [64]:
(array > 20) & (array < 50)

array([[False, False, False, False, False],
       [False,  True,  True,  True, False],
       [False, False, False, False, False]])

In [65]:
#Not (reverse version)
~(array > 20) & (array < 50)

array([[ True,  True,  True,  True,  True],
       [ True, False, False, False, False],
       [ True,  True,  True,  True,  True]])

In [66]:
array[~ (array > 20) & (array < 50)]

array([ 1,  2,  3,  4,  5, 11, 13, 14, 15, 16, 17])

np.any()

In [67]:
#Obtain the boolean value that matches our specified conditions
np.any(array > 20) #Any of the passed array has True boolean value

True

In [68]:
#Vertical
np.any(array > 20, axis = 0) #Any of the cols has True, the resulting cols from np.any() will be True 

array([False,  True,  True,  True,  True])

In [69]:
#Horizontal
np.any(array > 20, axis = 1)

array([False,  True, False])

np.all()

In [70]:
#True will be returned when all the values passed the specified condition
np.all(array > 20)

False

In [71]:
np.all(array > 20, axis = 0)

array([False, False, False, False, False])

In [72]:
np.all(array > 20, axis = 1)

array([False, False, False])

### Ravel, Flatten, Sqeeze

In [73]:
demo = np.arange(12)
demo.reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [74]:
demo.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [75]:
np.ravel(demo)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [76]:
demo.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [77]:
demo.squeeze()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In reshape one shape dimension can be -1. In this case, the value is inferred from the length of the array and remaining dimensions.

In [78]:
print(demo.reshape(4, 3))
print(demo.reshape(-1))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [79]:
print(demo.reshape(1, -1))
print(demo.reshape(2, -1))

[[ 0  1  2  3  4  5  6  7  8  9 10 11]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [80]:
print(demo.reshape(3, -1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [81]:
print(demo.reshape(-1, 1))

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]
